	soc_system u0 (
		.adc_fifo_0_st_sink_data               (<connected-to-adc_fifo_0_st_sink_data>),               //             adc_fifo_0_st_sink.data
		.adc_fifo_0_st_sink_valid              (<connected-to-adc_fifo_0_st_sink_valid>),              //                               .valid
		.adc_fifo_0_st_sink_ready              (<connected-to-adc_fifo_0_st_sink_ready>),              //                               .ready
		.adc_fifo_0_st_sink_startofpacket      (<connected-to-adc_fifo_0_st_sink_startofpacket>),      //                               .startofpacket
		.adc_fifo_0_st_sink_endofpacket        (<connected-to-adc_fifo_0_st_sink_endofpacket>),        //                               .endofpacket
		.adc_fifo_0_st_sink_empty              (<connected-to-adc_fifo_0_st_sink_empty>),              //                               .empty
		.button_pio_external_connection_export (<connected-to-button_pio_external_connection_export>), // button_pio_external_connection.export
		.clk_clk                               (<connected-to-clk_clk>),                               //                            clk.clk
		.clock_bridge_0_out_clk_clk            (<connected-to-clock_bridge_0_out_clk_clk>),            //         clock_bridge_0_out_clk.clk
		.dipsw_pio_external_connection_export  (<connected-to-dipsw_pio_external_connection_export>),  //  dipsw_pio_external_connection.export
		.hps_0_f2h_cold_reset_req_reset_n      (<connected-to-hps_0_f2h_cold_reset_req_reset_n>),      //       hps_0_f2h_cold_reset_req.reset_n
		.hps_0_f2h_debug_reset_req_reset_n     (<connected-to-hps_0_f2h_debug_reset_req_reset_n>),     //      hps_0_f2h_debug_reset_req.reset_n
		.hps_0_f2h_stm_hw_events_stm_hwevents  (<connected-to-hps_0_f2h_stm_hw_events_stm_hwevents>),  //        hps_0_f2h_stm_hw_events.stm_hwevents
		.hps_0_f2h_warm_reset_req_reset_n      (<connected-to-hps_0_f2h_warm_reset_req_reset_n>),      //       hps_0_f2h_warm_reset_req.reset_n
		.hps_0_h2f_reset_reset_n               (<connected-to-hps_0_h2f_reset_reset_n>),               //                hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>), //                   hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),   //                               .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),   //                               .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),   //                               .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),   //                               .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),   //                               .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),   //                               .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),    //                               .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>), //                               .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>), //                               .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>), //                               .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),   //                               .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),   //                               .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),   //                               .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),     //                               .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),      //                               .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),      //                               .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),     //                               .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),      //                               .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),      //                               .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),      //                               .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),      //                               .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),      //                               .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),      //                               .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),      //                               .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),      //                               .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),      //                               .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),      //                               .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),     //                               .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),     //                               .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),     //                               .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),     //                               .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim1_inst_CLK    (<connected-to-hps_0_hps_io_hps_io_spim1_inst_CLK>),    //                               .hps_io_spim1_inst_CLK
		.hps_0_hps_io_hps_io_spim1_inst_MOSI   (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MOSI>),   //                               .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_hps_io_spim1_inst_MISO   (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MISO>),   //                               .hps_io_spim1_inst_MISO
		.hps_0_hps_io_hps_io_spim1_inst_SS0    (<connected-to-hps_0_hps_io_hps_io_spim1_inst_SS0>),    //                               .hps_io_spim1_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),     //                               .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),     //                               .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),     //                               .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),     //                               .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA     (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),     //                               .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL     (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),     //                               .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),  //                               .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),  //                               .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),  //                               .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),  //                               .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),  //                               .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),  //                               .hps_io_gpio_inst_GPIO61
		.led_pio_external_connection_export    (<connected-to-led_pio_external_connection_export>),    //    led_pio_external_connection.export
		.memory_mem_a                          (<connected-to-memory_mem_a>),                          //                         memory.mem_a
		.memory_mem_ba                         (<connected-to-memory_mem_ba>),                         //                               .mem_ba
		.memory_mem_ck                         (<connected-to-memory_mem_ck>),                         //                               .mem_ck
		.memory_mem_ck_n                       (<connected-to-memory_mem_ck_n>),                       //                               .mem_ck_n
		.memory_mem_cke                        (<connected-to-memory_mem_cke>),                        //                               .mem_cke
		.memory_mem_cs_n                       (<connected-to-memory_mem_cs_n>),                       //                               .mem_cs_n
		.memory_mem_ras_n                      (<connected-to-memory_mem_ras_n>),                      //                               .mem_ras_n
		.memory_mem_cas_n                      (<connected-to-memory_mem_cas_n>),                      //                               .mem_cas_n
		.memory_mem_we_n                       (<connected-to-memory_mem_we_n>),                       //                               .mem_we_n
		.memory_mem_reset_n                    (<connected-to-memory_mem_reset_n>),                    //                               .mem_reset_n
		.memory_mem_dq                         (<connected-to-memory_mem_dq>),                         //                               .mem_dq
		.memory_mem_dqs                        (<connected-to-memory_mem_dqs>),                        //                               .mem_dqs
		.memory_mem_dqs_n                      (<connected-to-memory_mem_dqs_n>),                      //                               .mem_dqs_n
		.memory_mem_odt                        (<connected-to-memory_mem_odt>),                        //                               .mem_odt
		.memory_mem_dm                         (<connected-to-memory_mem_dm>),                         //                               .mem_dm
		.memory_oct_rzqin                      (<connected-to-memory_oct_rzqin>),                      //                               .oct_rzqin
		.pio_0_external_connection_export      (<connected-to-pio_0_external_connection_export>),      //      pio_0_external_connection.export
		.pio_1_external_connection_export      (<connected-to-pio_1_external_connection_export>),      //      pio_1_external_connection.export
		.pio_dg_external_connection_export     (<connected-to-pio_dg_external_connection_export>),     //     pio_dg_external_connection.export
		.pll_0_locked_export                   (<connected-to-pll_0_locked_export>),                   //                   pll_0_locked.export
		.pll_0_outclk1_clk                     (<connected-to-pll_0_outclk1_clk>),                     //                  pll_0_outclk1.clk
		.reset_reset_n                         (<connected-to-reset_reset_n>),                         //                          reset.reset_n
		.reset_bridge_0_out_reset_reset_n      (<connected-to-reset_bridge_0_out_reset_reset_n>),      //       reset_bridge_0_out_reset.reset_n
		.slave_io_0_user_interface_dataout_0   (<connected-to-slave_io_0_user_interface_dataout_0>),   //      slave_io_0_user_interface.dataout_0
		.slave_io_0_user_interface_dataout_1   (<connected-to-slave_io_0_user_interface_dataout_1>),   //                               .dataout_1
		.slave_io_0_user_interface_dataout_2   (<connected-to-slave_io_0_user_interface_dataout_2>),   //                               .dataout_2
		.slave_io_0_user_interface_dataout_3   (<connected-to-slave_io_0_user_interface_dataout_3>),   //                               .dataout_3
		.slave_io_0_user_interface_dataout_4   (<connected-to-slave_io_0_user_interface_dataout_4>),   //                               .dataout_4
		.slave_io_0_user_interface_dataout_5   (<connected-to-slave_io_0_user_interface_dataout_5>),   //                               .dataout_5
		.slave_io_0_user_interface_dataout_6   (<connected-to-slave_io_0_user_interface_dataout_6>),   //                               .dataout_6
		.slave_io_0_user_interface_dataout_7   (<connected-to-slave_io_0_user_interface_dataout_7>),   //                               .dataout_7
		.slave_io_0_user_interface_dataout_8   (<connected-to-slave_io_0_user_interface_dataout_8>),   //                               .dataout_8
		.slave_io_0_user_interface_dataout_9   (<connected-to-slave_io_0_user_interface_dataout_9>),   //                               .dataout_9
		.slave_io_0_user_interface_dataout_10  (<connected-to-slave_io_0_user_interface_dataout_10>),  //                               .dataout_10
		.slave_io_0_user_interface_dataout_11  (<connected-to-slave_io_0_user_interface_dataout_11>),  //                               .dataout_11
		.slave_io_0_user_interface_dataout_12  (<connected-to-slave_io_0_user_interface_dataout_12>),  //                               .dataout_12
		.slave_io_0_user_interface_dataout_13  (<connected-to-slave_io_0_user_interface_dataout_13>),  //                               .dataout_13
		.slave_io_0_user_interface_dataout_14  (<connected-to-slave_io_0_user_interface_dataout_14>),  //                               .dataout_14
		.slave_io_0_user_interface_dataout_15  (<connected-to-slave_io_0_user_interface_dataout_15>),  //                               .dataout_15
		.slave_io_0_user_interface_datain_0    (<connected-to-slave_io_0_user_interface_datain_0>),    //                               .datain_0
		.slave_io_0_user_interface_datain_1    (<connected-to-slave_io_0_user_interface_datain_1>),    //                               .datain_1
		.slave_io_0_user_interface_datain_2    (<connected-to-slave_io_0_user_interface_datain_2>),    //                               .datain_2
		.slave_io_0_user_interface_datain_3    (<connected-to-slave_io_0_user_interface_datain_3>),    //                               .datain_3
		.slave_io_0_user_interface_datain_4    (<connected-to-slave_io_0_user_interface_datain_4>),    //                               .datain_4
		.slave_io_0_user_interface_datain_5    (<connected-to-slave_io_0_user_interface_datain_5>),    //                               .datain_5
		.slave_io_0_user_interface_datain_6    (<connected-to-slave_io_0_user_interface_datain_6>),    //                               .datain_6
		.slave_io_0_user_interface_datain_7    (<connected-to-slave_io_0_user_interface_datain_7>),    //                               .datain_7
		.slave_io_0_user_interface_datain_8    (<connected-to-slave_io_0_user_interface_datain_8>),    //                               .datain_8
		.slave_io_0_user_interface_datain_9    (<connected-to-slave_io_0_user_interface_datain_9>),    //                               .datain_9
		.slave_io_0_user_interface_datain_10   (<connected-to-slave_io_0_user_interface_datain_10>),   //                               .datain_10
		.slave_io_0_user_interface_datain_11   (<connected-to-slave_io_0_user_interface_datain_11>),   //                               .datain_11
		.slave_io_0_user_interface_datain_12   (<connected-to-slave_io_0_user_interface_datain_12>),   //                               .datain_12
		.slave_io_0_user_interface_datain_13   (<connected-to-slave_io_0_user_interface_datain_13>),   //                               .datain_13
		.slave_io_0_user_interface_datain_14   (<connected-to-slave_io_0_user_interface_datain_14>),   //                               .datain_14
		.slave_io_0_user_interface_datain_15   (<connected-to-slave_io_0_user_interface_datain_15>),   //                               .datain_15
		.slave_io_0_user_interface_write       (<connected-to-slave_io_0_user_interface_write>),       //                               .write
		.slave_io_0_user_interface_read        (<connected-to-slave_io_0_user_interface_read>),        //                               .read
		.slave_io_0_user_interface_chipselect  (<connected-to-slave_io_0_user_interface_chipselect>),  //                               .chipselect
		.slave_io_0_user_interface_byteenable  (<connected-to-slave_io_0_user_interface_byteenable>)   //                               .byteenable
	);

